### ISSUE TITLE
improve robustness of golden_method function

### ISSUE THREAD

**Issue by albep** [spencerlyon2/CompEcon.jl#2]
It turns out that if x1 and x2 are 1-dimensional, but the f function produces 2-dimensional vectors, then we get this error:

ERROR: BoundsError()
 in getindex_bool_1d at array.jl:285
 in getindex at array.jl:299
 in golden_method at /home/ap/.julia/v0.3/CompEcon/src/optimization.jl:19

**Comment by sglyon** [comment]
@albep is this still an issue? Can you provide a minimal test case that highlights the problem?

**Comment by albep** [comment]
@spencerlyon2 I think the easiest way to highlight the problem would be to take the code I gave you that uses this package, and modify the F function optimized by golden_method to return 2-dimensional vectors, instead of 1-dimensional. I worked around the issue by having F return 1-dimesional vectors, I don't know if the issue is still relevant then

**Comment by sglyon** [comment]
When I wrote the function, my understanding was that it applied golden method element wise to 1-dimensional arrays. This means that the function passed to the argument should take a 1-dimensional array and return a 1-dimensional array.

If you have a more general use case in mind, it would be great to generalize the method.

**Comment by albep** [comment]
Yes that's fine. I was thinking that having golden_method vectorize the
output of the function from 2-dim vector to 1-dim vector was an improvement
(because the vector function you are optimizing typically has matrix
multiplications in it, so it will naturally return 2-dim vectors unless you
explicitly vectorize the matrix multiplication). Essentially instead of
having vectorize in the objective function, I'd put it in the golden_method
function.

If you don't feel that's enough of a case to change it, I'm perfectly fine
with how golden_method works now!

**Comment by sglyon** [comment]
Oh ok, I see. 

My personal preference is to **not** transform output of user functions in  library functions, but rather let users adapt their code to the given API (meaning `golden_method` accepts a function that maps R^n -> R^n not R^n->R^{N x 1}).

However, in this case it _might_ be ok because if `vec(f(x))` doesn't produce a 1d array of the same length as `lb` and `ub`, the routine will throw an error. So it should be a pretty safe transformation

**Comment by sglyon** [comment]
^^ see edit above (added word **not**)

**Comment by sglyon** [comment]
Closing as I think this is ok.

@albep please re-open if you think there is still room for improvement here.
