### ISSUE TITLE
LoadError: MethodError: no method matching exp

### ISSUE THREAD

**Issue by zlqs1985** [spencerlyon2/CompEcon.jl#40]
I tested the working example (which I named by ChebshevApp.jl) and have the following error messages. My Julia version is 1.5.0

`julia> include("ChebshevApp.jl")
[ Info: Precompiling CompEcon [1375f997-1772-542d-b6fa-a8ee39124556]
WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\user\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\user\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\user\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:924 overwritten in module Optim at C:\Users\user\.julia\packages\Optim\Agd3B\src\multivariate\precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: MethodError: no method matching exp(::Array{Float64,1})
Closest candidates are:
  exp(::Float16) at math.jl:1144
  exp(::Missing) at math.jl:1197
  exp(::BigFloat) at mpfr.jl:603
  ...
Stacktrace:
 [1] f(::Array{Float64,1}) at C:\Users\user\Documents\Julia\ChebshevApp.jl:3
 [2] funfitf(::Basis{1,Tuple{ChebParams{Float64}}}, ::Function) at C:\Users\user\.julia\packages\BasisMatrices\PZ1uM\src\interp.jl:68
 [3] funfitf(::Dict{Symbol,Any}, ::Function) at C:\Users\user\.julia\packages\CompEcon\9POAs\src\core.jl:134
 [4] top-level scope at C:\Users\user\Documents\Julia\ChebshevApp.jl:16
 [5] include(::String) at .\client.jl:457
 [6] top-level scope at none:1
in expression starting at C:\Users\user\Documents\Julia\ChebshevApp.jl:16`

**Comment by cc7768** [comment]
This looks like we probably need to be using `exp.(x)` rather than `exp(x)` for an array `x`.

Does changing the function definition (in line 3) to `f(x) = exp.(-x)` work?

**Comment by IljaK91** [comment]
Yes, changing the function definition works!
